make default aspect DropShadows instead of Inset for UbuntuShape
ubports/ubuntu-ui-toolkit pull request #22
Opened 2018-10-16 15:36 UTC by mymike00

this changes the default apsect of the UbuntuShape from Inset to DropShadow
**NOTE**: this will change the look of a load of components that uses the ubuntushape like buttons, switches, checkboxes, optionselectors and also the textfield in the messaging-app
I really like it but someone maybe won't. here are some screenshots

optionselector and checkboxes
![optionselector and checkboxes](https://user-images.githubusercontent.com/28359593/47028345-82bd1080-d169-11e8-8f24-c3659a5452ef.png)

switches
![switches](https://user-images.githubusercontent.com/28359593/47028434-b009be80-d169-11e8-99f8-1f991a2862d6.png)

buttons
![buttons](https://user-images.githubusercontent.com/28359593/47028538-dc253f80-d169-11e8-8019-ab5db9a1e376.png)

2018-10-16 15:36 UTC, mymike00 commented on src/UbuntuToolkit/ucubuntushape.cpp
> +    \li \b UbuntuShape.DropShadow - outer non-blurred shadow slightly moved downwards
is this diescription ok?

2018-10-16 15:37 UTC, mymike00 commented on src/UbuntuToolkit/ucubuntushape.cpp
> +            aspect = DropShadow;
not very very sure I have to change this also but I think it should...

2018-10-17 22:15 UTC, nfsprodriver commented
I love the new optic. It bring a even more modern flare to Ubuntu Touch.

2018-11-09 02:05 UTC, cibersheep commented
Interesting. I'm not a big fun if the Inset.
I like your changes for the buttons and textfields but not for the optionselectors and switches.

The positive aspect is that only changes the defaults but the downside is that we might want to change the behaviour on some elements.

2018-11-09 07:40 UTC, mymike00 commented
I like them also like this, but it wouldn't be so much effort changing also the components...

2018-11-09 17:37 UTC, cibersheep commented
Ok. Let's try this in the devel. If we feel like, we can revert it or modify some components before arrives RC.
Do you think?

2018-11-09 21:31 UTC, mymike00 commented
Yeah, let's merge!

2018-11-12 17:20 UTC, cibersheep commented
You got green light! Wweeeee... after OTA6 (which is «at the turn of the corner» meaning that will happen really soon).
So, if you don't mind waiting a little bit more, we will see your changes very soon.
THANKS!

2018-12-10 23:22 UTC, cibersheep commented
So, has it arrive the time to try to merge this?
I see there's an error in the building tests...

2018-12-21 09:35 UTC, mymike00 commented
Yeah, how to solve them? just trigger again the build?

2019-02-08 15:22 UTC, UniversalSuperBox commented
Thanks to https://github.com/ubports/ubuntu-ui-toolkit/pull/30 and https://github.com/ubports/ubuntu-ui-toolkit/pull/31, we finally have everything in place to build the UITK again and PRs can be merged.

2019-02-08 15:27 UTC, UniversalSuperBox requested changes
@NeoTheThird brought up a good point with this PR: we would need to test many apps with it before we merge. This could break the design of any app which uses the UbuntuShape, even relatively small apps like [8192](https://open-store.io/app/8192.neothethird).

An ideal test plan would be:

1. Wait for a good time in the `xenial_-_edge` cycle (now is not a good time)
2. Merge this into edge and encourage testers to try out all their apps

Alternatively, you can get people to install this PR (`sudo ubports-qa install PR-22`) and test out a lot of apps to see if any break, then report the breakage to the authors. This might be the faster solution.

Let me know what you think.

2019-02-08 19:58 UTC, mymike00 commented
I'd prefer to ask in the QA team/main supergroups for tester to try this PR, imho more people can test it and it'd faster.

2019-02-10 20:51 UTC, cibersheep commented
Ouh. Charging my testing device :)

2019-02-22 18:07 UTC, cibersheep commented
I have tried to install this but I can't see any change in the ui. Might it be a qrc (qml cached file?)

2019-02-24 20:14 UTC, mymike00 commented
@cibersheep Mmh that's odd. when I installed it with crossbuilder I see them after the first reboot iirc. I tried now, after an update, with `ubports-qa` but I cannot make it working...
```
$ sudo ubports-qa install ubuntu-ui-toolkit 22
CRITICAL:ubports-qa:Jenkins build not found
```

2019-02-25 16:12 UTC, UniversalSuperBox commented
You might need to do `ubports/reponame` for some reason.

2019-03-15 14:29 UTC, mymike00 commented
I noticed that with colored ubuntu shapes you don't notice too much the drop shadows while it gave a better look than the inset shadow imho.
yeah, I agree that the option selector isn't that great but if we make it with the inset shadow it would be the only component different from others...
but, all in all, this pr doesn't introduce so drastic changes therefore I think it could be merged and then if a lot of people say to prefer some components with the old look then we can fix it later
remember that there's also another ubuntu shape aspect option, which is flat, with no shadow at all. it might be nicer for the option selector...

2019-03-15 19:10 UTC, dobey commented
> remember that there's also another ubuntu shape aspect option, which is flat, with no shadow at all. it might be nicer for the option selector...

I think flat would probably look better for all the cases. Only the toggle switches might be a little odd, but it should already be specifying inset and outset for the shadow types of its elements, I would think.

2019-03-15 23:17 UTC, mymike00 commented
No, I don't think they do...
to decide the default aspect idk, it'd prefer dropshadow because when you use pure ubuntuShape for (usually) images/logo it fits better while other uitk components could have a specific aspect for their selves...
I'll may do some tests and see what looks nicer

2019-03-18 23:35 UTC, cibersheep commented
I'm also a fan of flat. But I wasn't able to test this PR yet. Can you believe that?

2019-03-19 06:06 UTC, mymike00 commented
I wasn't able to install it with ubports-qa iirc, only with crossbuilder...

2019-04-13 12:31 UTC, mymike00 commented
so I tested with default aspect `Flat` and `Switch` and `OptionSelector` doesn't look nice...
we have to decide if we prefer them `Inset` or `DropShadow`, let me know
![immagine](https://user-images.githubusercontent.com/28359593/56079738-8ff54800-5df8-11e9-8aa6-de94f09d98d2.png)
![immagine](https://user-images.githubusercontent.com/28359593/56079742-9a174680-5df8-11e9-80c6-99013d415e62.png)
![immagine](https://user-images.githubusercontent.com/28359593/56079745-9d123700-5df8-11e9-813a-48c1bf79e2fe.png)

2019-04-28 19:59 UTC, mymike00 commented
what are we going to do with this?
the thing is that I don't like the Inset shadow by default (but looks good in some component like OptionSelector, Switch, CheckBox, etc...). the other 2 choices are Flat or DropShadows: usually UbuntuShape is used for images, app icons, buttons ... that have colored bg. in those situation (quite always) I think it suits better the DropShadows so I'd make it the default.
are you ok?

2019-04-28 22:19 UTC, cibersheep commented
Sounds ok :)

2019-07-07 10:42 UTC, mymike00 commented
Now `OptionSelector`, `Switch` and `CheckBox` use bt default `Inset` aspect (which is their default look now, before this PR) while the default for everything else is DropShadow

2019-09-08 20:09 UTC, UniversalSuperBox commented
I've reconfigured the CI so pull requests will build now. It'll be a little while until yours is finished, Jenkins is quite upset with me for that.

This PR has become quite littered with commits from `xenial`. If I can ask it of you, could you create a new PR built off of the current `xenial` branch with only your changes added? That will ensure we're only viewing and testing your changes.

2019-09-08 20:17 UTC, mymike00 commented
Sure, i'm gonna do it this week

2019-09-08 20:17 UTC, closed without merging