Make text of a Button take strokColor if it's defined
ubports/ubuntu-ui-toolkit pull request #88
Opened 2020-08-09 12:15 UTC by cibersheep

Fix: #85

2020-08-09 15:56 UTC, cibersheep commented
Oh, fails build for amd64:
https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fubuntu-ui-toolkit/detail/PR-88/1/pipeline/#step-33-log-2221

Is something I should do here?

2020-10-09 18:49 UTC, cibersheep commented
Any news on this?

2020-10-09 21:49 UTC, dobey requested changes

2020-10-09 21:49 UTC, dobey commented on src/imports/Components/Themes/Ambiance/1.3/ButtonStyle.qml
> +           except that stroke is defined that will use strokeColor: should fix https://github.com/ubports/ubuntu-ui-toolkit/issues/85
I don't think we should have comments in code that are "should fix" in reference to issues. Instead, we should test that the issue is fixed. I think the comment text could use some improvement too, though it's not entirely clear to me from the overall comment there how this was meant to be used.

2020-10-09 23:07 UTC, cibersheep commented on src/imports/Components/Themes/Ambiance/1.3/ButtonStyle.qml
> +           except that stroke is defined that will use strokeColor: should fix https://github.com/ubports/ubuntu-ui-toolkit/issues/85
Done :)

2020-10-10 00:43 UTC, cibersheep commented
Tested with ubports-qa.
Before and after

![imatge](https://user-images.githubusercontent.com/6640041/95641403-5ad7bd80-0aa2-11eb-85be-6e32ebaea547.png)

2020-10-13 16:20 UTC, dobey commented on src/imports/Components/Themes/Ambiance/1.3/ButtonStyle.qml
> +           except that stroke is defined that will use strokeColor: should fix https://github.com/ubports/ubuntu-ui-toolkit/issues/85
I didn't mean the entire comment should be removed. Just that the wording doesn't seem right. Perhaps just appending `, when strokeColor is not specified.` to the end of the comment rather than saying it should fix something. :)

2020-10-13 20:14 UTC, cibersheep commented on src/imports/Components/Themes/Ambiance/1.3/ButtonStyle.qml
> +           except that stroke is defined that will use strokeColor: should fix https://github.com/ubports/ubuntu-ui-toolkit/issues/85
I see... hi hi hi
If you think the comment is useful... commit in 3...

2020-10-13 21:44 UTC, dobey approved these changes
Looks OK. Thanks.

2020-10-13 21:44 UTC, merged

2020-10-29 13:44 UTC, UniversalSuperBox commented
To test:

Try out your favorite apps. If you can read all the buttons, this change likely did not cause a regression.

2020-10-29 22:59 UTC, cibersheep commented
> To test:

Thanks :)
Some apps that have stroke buttons are: Morph (triggering the Bottom Edge menu) and the welcome tutorial